FROM hub.furycloud.io/mercadolibre/java:1.11-runtime-mini

# Enable JMX
ENV JAVA_OPTS="$JAVA_OPTS -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Dcom.sun.management.jmxremote.local.only=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false"

# IGNORE STATUS New Relic
ENV NEWRELIC_EXPECTED_STATUS_CODES=400,401,403,404,405,409,422,423
