package com.mercadolibre.planning.model.me.usecases.backlog;

import com.google.common.collect.Sets;
import com.mercadolibre.planning.model.me.entities.monitor.ProcessDetail;
import com.mercadolibre.planning.model.me.entities.monitor.UnitMeasure;
import com.mercadolibre.planning.model.me.entities.monitor.VariablesPhoto;
import com.mercadolibre.planning.model.me.gateways.backlog.dto.Consolidation;
import com.mercadolibre.planning.model.me.gateways.planningmodel.dtos.ProcessName;
import com.mercadolibre.planning.model.me.usecases.backlog.dtos.BacklogStatsByDate;

import java.time.Duration;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.Comparator;
import java.util.List;
import java.util.Set;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import static java.util.Comparator.naturalOrder;

abstract class GetConsolidatedBacklog {

    private static final long MAX_ALLOWED_MINUTES_SHIFT = 5L;

    /**
     * Gets, from the received consolidated backlog trajectory, the date when the latest backlog
     * photo was taken, or the {@code defaultDate} if either the received {@code consolidations}
     * list is empty or the latest photo date is more than five minutes earlier than the
     * {@code defaultDate}. TODO Explain why the second is necessary.
     *
     * @return the date mentioned date.
     */
    protected Instant getDateWhenLatestPhotoWasTaken(
            final List<Consolidation> consolidationTrajectory,
            final Instant defaultDate
    ) {
        return consolidationTrajectory.stream()
                .map(Consolidation::getDate)
                .max(naturalOrder())
                .filter(date -> date.until(defaultDate, ChronoUnit.MINUTES)
                        < MAX_ALLOWED_MINUTES_SHIFT)
                .orElse(defaultDate);
    }

    /** Truncates to hours the dates at which the backlog photos were taken on.*/
    protected List<Consolidation> truncateToHoursTheTakenOnDatesExceptFor(
            final List<Consolidation> consolidations,
            final Instant theDateThatIsKeptAsIs
    ) {
        return consolidations.stream()
                .map(cellsGroupSum -> {
                    final Instant date = theDateThatIsKeptAsIs
                            .equals(cellsGroupSum.getDate())
                            ? theDateThatIsKeptAsIs
                            : cellsGroupSum.getDate().truncatedTo(ChronoUnit.HOURS);

                    return new Consolidation(
                            date,
                            cellsGroupSum.getKeys(),
                            cellsGroupSum.getTotal()
                    );
                })
                .collect(Collectors.toList());
    }

    /**
     * Gives a copy of the received list of consolidations with the empty consolidations slots
     * filled with consolidations generated by the received {@code consolidationSupplier}.
     * There is a consolidation slot at every hour transition contained in the specified time
     * interval, plus one more slot at the end of the interval (dateTo) if it is not an hour
     * boundary.
     *
     * @param consolidations the list of consolidations of the latest backlog photos with the date
     *     truncated to hours except the last <--- FIXME: complex assumptions is a
     *     sign of lack of proper data types. The last photo should be out of the
     *     list in another field.
     * @param dateFrom the hour of the first consolidation slot.
     * @param dateTo the date of the last consolidation slot.
     * @param consolidationSupplier a function from {@link Instant} to {@link Consolidation}.
     * @return a copy of the received list of consolidations with the empty consolidations slots
     *     filled with consolidations generated by the received {@code consolidationSupplier}.
     */
    protected List<Consolidation> fillMissing(
            final List<Consolidation> consolidations,
            final Instant dateFrom,
            final Instant dateTo,
            final Function<Instant, Consolidation> consolidationSupplier
    ) {
        assert dateFrom.equals(dateFrom.truncatedTo(ChronoUnit.HOURS));

        final Set<Instant> currentDates = consolidations.stream()
                .map(Consolidation::getDate)
                .collect(Collectors.toSet());

        final long totalHours = ChronoUnit.HOURS.between(dateFrom, dateTo);

        final Set<Instant> allHours = IntStream.rangeClosed(0, (int) totalHours)
                .mapToObj(hours -> dateFrom.plus(Duration.ofHours(hours)))
                .collect(Collectors.toSet());
        allHours.add(dateTo);

        final List<Consolidation> missing = Sets.difference(allHours, currentDates).stream()
                .map(consolidationSupplier)
                .collect(Collectors.toList());

        missing.addAll(consolidations);

        return missing;
    }

    protected ProcessDetail build(final ProcessName process,
                                  final Instant currentDatetime,
                                  final List<BacklogStatsByDate> backlogs) {

        final List<VariablesPhoto> backlog = backlogs
                .stream()
                .map(stats -> toBacklogByDate(stats, currentDatetime))
                .sorted(Comparator.comparing(VariablesPhoto::getDate))
                .collect(Collectors.toList());

        final UnitMeasure totals = backlog.stream()
                .filter(b -> b.getDate().equals(currentDatetime))
                .findFirst()
                .map(VariablesPhoto::getCurrent)
                .map(measure -> new UnitMeasure(
                        measure.getUnits(),
                        measure.getMinutes() == null ? Integer.valueOf(0) : measure.getMinutes()))
                .orElse(new UnitMeasure(0, 0));

        return new ProcessDetail(process.getName(), totals, backlog);
    }

    private VariablesPhoto toBacklogByDate(
            final BacklogStatsByDate description,
            final Instant currentDatetime
    ) {
        final Instant date = currentDatetime.equals(description.getDate())
                ? currentDatetime
                : description.getDate().truncatedTo(ChronoUnit.HOURS);

        return VariablesPhoto.builder()
                .date(date)
                .current(description.getTotal())
                .historical(description.getHistorical())
                .minLimit(description.getMinLimit())
                .maxLimit(description.getMaxLimit())
                .build();
    }
}
